/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/arm_termie_left.gltf
*/

import React, { useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { Mesh } from './Mesh.jsx';

export function ArmTermieRightTwo(props) {
  const { nodes, materials } = useGLTF(
    'https://model-painter.s3.eu-west-2.amazonaws.com/arm_termie_right_two.gltf'
  );
  const [colours, setColours] = useState([]);
  const [newNodeArr, setNewNodeArr] = useState([]);

  useEffect(() => {
    const nodeArr = Object.keys(nodes);
    setNewNodeArr(nodeArr);
  }, [nodes]);

  return (
    <group {...props}>
      {newNodeArr.map((node, index) => {
        if (!nodes[node].geometry) return null;
        return (
          <Mesh
            key={`${index}-armRTwo`}
            nodeGeometry={nodes[node].geometry}
            position={nodes[node].position}
            material={nodes[node].material}
            currentPaint={props.currentPaint}
            paintRef={props.paintRef}
            name={node}
            show={props.show}
            lights={
              node === 'Arm_with_Captain_sword013' && {
                pos: [
                  [-17, -1.8, 17],
                  [-20, 10.8, 28],
                  [-12, -2, 20],
                  [-10, 5.8, 28],
                ],
                dist: 22,
              }
            }
          />
        );
      })}
    </group>
  );
}

useGLTF.preload(
  'https://model-painter.s3.eu-west-2.amazonaws.com/arm_termie_right_two.gltf'
);
