/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/skeleton.gltf
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function HelmetNightlord(props) {
  const { nodes } = useGLTF(
    'https://model-painter.s3.eu-west-2.amazonaws.com/skeleton.gltf'
  );

  return (
    <group {...props}>
      <mesh
        geometry={nodes.NightLordPrim.geometry}
        material={nodes.NightLordPrim.material}
        position={[0.01, 4.71, -0.21]}
        scale={1}
        show={props.show}
      />
    </group>
  );
}

useGLTF.preload(
  'https://model-painter.s3.eu-west-2.amazonaws.com/skeleton.gltf'
);
