/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/terminator_cloak.gltf
*/
import { memo, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { MemoMesh } from './Mesh.jsx';
import { PaintType } from '../paints';


interface ModelObjectProps {
  squadIndex: number;
  url: string;
  paintRef: React.RefObject<HTMLDivElement>;
  show: boolean;
  currentPaintRef: React.MutableRefObject<PaintType>;
  baseColor: PaintType;
  clone: boolean;
  showEdges: boolean;
  showPaintLabels: boolean;
  hoveredPaintLabelKey: string | null;
  setHoveredPaintLabelKey: React.Dispatch<React.SetStateAction<string | null>>;
  paintSyncTick: number;
  isSurfacePaintEnabled: boolean;
  surfaceAngleThreshold: number;
  surfaceBrushRadius: number;
  onPaintApplied: (payload: {
    paintKey: string;
    unitNumber: number;
    previousPaint: PaintType | string | null;
    nextPaint: PaintType | string;
  }) => void;
  isPaintingEnabled: boolean;
}

const buildPaintTargetId = (url: string, node: string) => `${url}::${node}`;

function ModelObjectComponent(props: ModelObjectProps) {
  const {
    squadIndex,
    url,
    paintRef,
    show,
    currentPaintRef,
    baseColor,
    clone,
    showEdges,
    showPaintLabels,
    hoveredPaintLabelKey,
    setHoveredPaintLabelKey,
    paintSyncTick,
    isSurfacePaintEnabled,
    surfaceAngleThreshold,
    surfaceBrushRadius,
    onPaintApplied,
    isPaintingEnabled,
  } = props;
  const { nodes } = useGLTF(url);
  const nodeKeys = useMemo(() => Object.keys(nodes), [nodes]);
  return (
    <group>
      {nodeKeys.map((node, index) => {
        if (!nodes[node] || !(nodes[node] as any).geometry) return null;
        return (
          <MemoMesh
            key={`${index}-${squadIndex}-${url}`}
            paintTargetId={buildPaintTargetId(url, node)}
            nodeGeometry={(nodes[node] as any).geometry}
            material={(nodes[node] as any).material}
            currentPaintRef={currentPaintRef}
            paintRef={paintRef}
            name={`${node}`}
            unitNumber={squadIndex}
            show={show}
            baseColor={baseColor}
            clone={clone}
            showEdges={showEdges}
            showPaintLabels={showPaintLabels}
            hoveredPaintLabelKey={hoveredPaintLabelKey}
            setHoveredPaintLabelKey={setHoveredPaintLabelKey}
            paintSyncTick={paintSyncTick}
            isSurfacePaintEnabled={isSurfacePaintEnabled}
            surfaceAngleThreshold={surfaceAngleThreshold}
            surfaceBrushRadius={surfaceBrushRadius}
            onPaintApplied={onPaintApplied}
            isPaintingEnabled={isPaintingEnabled}
          />
        );
      })}
    </group>
  );
}

export const ModelObject = memo(ModelObjectComponent);
