/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/terminator_cloak.gltf
*/
import { useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { Mesh } from './Mesh.jsx';
import { PaintType } from '../paints';


interface ModelObjectProps {
  squadIndex: number;
  url: string;
  paintRef: React.RefObject<HTMLDivElement>;
  show: boolean;
  currentPaint: PaintType;
  baseColor: PaintType;
  clone: boolean;
  showEdges: boolean;
  isPaintingEnabled: boolean;
}

export function ModelObject(props: ModelObjectProps) {
  const {
    squadIndex,
    url,
    paintRef,
    show,
    currentPaint,
    baseColor,
    clone,
    showEdges,
    isPaintingEnabled,
  } = props;
  const { nodes } = useGLTF(url);
  const nodeKeys = useMemo(() => Object.keys(nodes), [nodes]);
  return (
    <group>
      {nodeKeys.map((node, index) => {
        if (!nodes[node] || !(nodes[node] as any).geometry) return null;
        return (
          <Mesh
            key={`${index}-${squadIndex}-${url}`}
            nodeGeometry={(nodes[node] as any).geometry}
            material={(nodes[node] as any).material}
            currentPaint={currentPaint}
            paintRef={paintRef}
            name={`${node}`}
            unitNumber={squadIndex}
            show={show}
            baseColor={baseColor}
            clone={clone}
            showEdges={showEdges}
            isPaintingEnabled={isPaintingEnabled}
          />
        );
      })}
    </group>
  );
}
