/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/skeleton.gltf
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function ModelImport(props) {
  const { nodes } = useGLTF(
    'https://model-painter.s3.eu-west-2.amazonaws.com/skeleton.gltf'
  );
  return (
    <group>
      <group {...props} dispose={null} position={props.position}>
        <group position={[1, -42.5, 0]} rotation={[0, 1.4 * Math.PI, 0]}>
          {props.base}
        </group>
        <primitive
          object={nodes.Armature}
          rotation={[0, props.torsoTopBone * Math.PI, 0]}
        >
          <primitive object={nodes.Core}>
            <primitive
              rotation={[props.arm + 0, 0.5 * Math.PI, 0]}
              position={[10, 1, -4]}
              object={nodes.UpperArmL}
            >
              <group
                rotation={[0 * Math.PI, 0 * Math.PI, -0.48]}
                position={[1, 0, -2.3]}
              >
                {props.shoulderL}
              </group>
              <group position={[0, -3.2, -2]} rotation={[0, -0.5 * Math.PI, 0]}>
                {props.armL}
              </group>
            </primitive>
            <primitive
              rotation={[props.armRRot + 0, 0, 0]}
              position={[-11.4, -1, -4]}
              object={nodes.UpperArmR}
            >
              <group
                rotation={[0 * Math.PI, -0.5 * Math.PI, 0]}
                position={[0, 0, 0]}
              >
                {props.shoulderR}
              </group>
              <group
                position={[3, -3.2, -1]}
                rotation={[0 * Math.PI, 0 * Math.PI, 0 * Math.PI]}
              >
                {props.armR}
              </group>
            </primitive>
            <primitive
              object={nodes.Bone008}
              rotation={[0, props.neck, 0]}
              position={[0, -3.6, 0]}
            >
              {props.helmet}
            </primitive>
            <group rotation={[0, 1 * Math.PI, 0]} position={[0, -9, -9.0]}>
              {props.cloak}
            </group>
            <group rotation={[0, 0, 0]} position={[0, 7, -6.0]}>
              {props.ironCross}
            </group>

            <group position={[0, -9.8, -4.0]}>{props.torso}</group>
            <primitive
              rotation={[0, props.torsoBone + 0 * Math.PI, 0]}
              object={nodes.Spine}
            >
              <group scale={1.1} position={[-0.2, -6.5, 0.4]}>
                {props.legs}
              </group>
            </primitive>
          </primitive>
        </primitive>
      </group>
    </group>
  );
}

useGLTF.preload(
  'https://model-painter.s3.eu-west-2.amazonaws.com/skeleton.gltf'
);
