/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/spacehulk.gltf
*/

import React, { useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { Mesh } from './Mesh.jsx';
import { Light } from './Light.jsx';
export function Spacehulk(props) {
  const { nodes, materials } = useGLTF(
    'https://model-painter.s3.eu-west-2.amazonaws.com/spacehulk.gltf'
  );
  const [newNodeArr, setNewNodeArr] = useState([]);
  useEffect(() => {
    const nodeArr = Object.keys(nodes);
    setNewNodeArr(nodeArr);
  }, [nodes]);

  return (
    <group {...props}>
      <Light position={[0, 30, -40]} c="white" d={props.lighting * 50} i={1} />
      <Light
        position={[-40, 30, -40]}
        c="white"
        d={props.lighting * 50}
        i={1}
      />
      <Light
        position={[-80, 30, -40]}
        c="white"
        d={props.lighting * 50}
        i={1}
      />
      <Light position={[0, 30, 50]} c="white" d={props.lighting * 50} i={1} />
      <Light position={[-40, 30, 50]} c="white" d={props.lighting * 50} i={1} />
      <Light position={[-80, 30, 50]} c="white" d={props.lighting * 50} i={1} />
      <Light position={[0, 50, 0]} c="white" d={props.lighting * 50} i={1} />
      <Light
        position={[-40, 50, -40]}
        c="white"
        d={props.lighting * 50}
        i={1}
      />
      <Light
        position={[-80, 50, -40]}
        c="white"
        d={props.lighting * 50}
        i={1}
      />

      {newNodeArr.map((node, index) => {
        if (!nodes[node].geometry) return null;
        return (
          <Mesh
            key={`${index}-SPH`}
            nodeGeometry={nodes[node].geometry}
            position={nodes[node].position}
            material={nodes[node].material}
            currentPaint={props.currentPaint}
            paintRef={props.paintRef}
            name={node}
            show={props.show}
          />
        );
      })}
    </group>
  );
}

useGLTF.preload(
  'https://model-painter.s3.eu-west-2.amazonaws.com/spacehulk.gltf'
);
