/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/torso_termie.gltf
*/

import React, { useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { Mesh } from './Mesh.jsx';

export function TorsoTermie(props) {
  const { nodes, materials } = useGLTF(
    'https://model-painter.s3.eu-west-2.amazonaws.com/torso_termie.gltf'
  );
  const [colours, setColours] = useState([]);
  const [newNodeArr, setNewNodeArr] = useState([]);
  useEffect(() => {
    const nodeArr = Object.keys(nodes);
    setNewNodeArr(nodeArr);
  }, [nodes]);
  return (
    <group {...props} dispose={null}>
      {newNodeArr.map((node, index) => {
        if (!nodes[node].geometry) return null;
        return (
          <Mesh
            key={index}
            nodeGeometry={nodes[node].geometry}
            position={nodes[node].position}
            material={nodes[node].material}
            currentPaint={props.currentPaint}
            paintRef={props.paintRef}
            name={node}
            lights={
              node === 'Terminator_Torso003' && {
                pos: [
                  [-5.4, 18.5, 5],
                  [-6.3, 16.9, 5],
                ],
                dist: 2,
              }
            }
          />
        );
      })}
    </group>
  );
}

useGLTF.preload(
  'https://model-painter.s3.eu-west-2.amazonaws.com/torso_termie.gltf'
);
