/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/skeleton.gltf
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function TyranidSkeleton(props) {
  const { nodes } = useGLTF(
    'https://model-painter.s3.eu-west-2.amazonaws.com/skeleton.gltf'
  );
  return (
    <group>
      <group {...props} position={props.position}>
        <group position={[0, -9.8, -4.0]}>{props.torso}</group>
        <group position={[0, 10, 7.0]}>{props.head}</group>
        <group position={[0, 10, 7.0]}>{props.arm}</group>
      </group>
    </group>
  );
}

useGLTF.preload(
  'https://model-painter.s3.eu-west-2.amazonaws.com/skeleton.gltf'
);
