/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/wall.gltf
*/

import React, { useEffect, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { Mesh } from './Mesh.jsx';

export function Wall(props) {
  const { nodes, materials } = useGLTF(
    'https://model-painter.s3.eu-west-2.amazonaws.com/wall.gltf'
  );
  const [colours, setColours] = useState([]);
  const [newNodeArr, setNewNodeArr] = useState([]);

  useEffect(() => {
    const nodeArr = Object.keys(nodes);
    const newColours = [];
    for (let i = 0; i < nodeArr.length; i++) {
      newColours.push('#173164');
    }
    setColours(newColours);
    setNewNodeArr(nodeArr);
  }, [nodes]);
  if (!colours) return null;
  return (
    <group {...props} dispose={null}>
      {newNodeArr.map((node, index) => {
        if (!nodes[node].geometry) return null;
        return (
          <Mesh
            key={index}
            nodeGeometry={nodes[node].geometry}
            position={nodes[node].position}
          />
        );
      })}
    </group>
  );
}

useGLTF.preload('https://model-painter.s3.eu-west-2.amazonaws.com/wall.gltf');
