/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/dild.gltf
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Dild(props) {
  const { nodes } = useGLTF('/dild.gltf');
  const { boneConfig } = props;
  const maxPush =
    -1.3 + boneConfig.b_R_Leg1.rotation[0] > 0
      ? 0
      : -1.3 + boneConfig.b_R_Leg1.rotation[0];
  return (
    <group
      {...props}
      dispose={null}
      scale={0.025}
      position={[0, maxPush, 0.03]}
    >
      <mesh geometry={nodes.Sphere.geometry} position={[0, 4.3, 0]} />
    </group>
  );
}

useGLTF.preload('/dild.gltf');
