/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/skeleton.gltf
*/

import React from 'react';
import { ModelImport } from './modelParts/SkeletonGaunt.jsx';
import { ModelObject } from './modelParts/ModelObject.jsx';
export function Gaunt(props) {
  const {
    currentPaint,
    armRRot,
    paintRef,
    show,
    squadIndex,
    baseColor,
    clone,
  } = props;

  function modelFactory(url) {
    return (
      <ModelObject
        currentPaint={currentPaint}
        paintRef={paintRef}
        show={show ? 1 : 0}
        squadIndex={squadIndex}
        url={url}
        baseColor={baseColor}
        clone={clone}
      />
    );
  }

  return (
    <group>
      <ModelImport
        torsoBone={props.torsoBone}
        neck={props.neck}
        torso={modelFactory('gaunt.glb')}
        armRRot={armRRot}
        base={
          <ModelObject
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
            squadIndex={squadIndex}
            url="base_small.glb"
            baseColor={baseColor}
            clone={clone}
          />
        }
        currentPaint={props.currentPaint}
        torsoTopBone={props.torsoTopBone}
        paintRef={paintRef}
        baseColor={baseColor}
      />
    </group>
  );
}
