/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/marine-mini.gltf
*/
import React, { useEffect } from 'react';
import { useGLTF } from '@react-three/drei';

function getBones() {}

export function Model(props) {
  const { nodes, materials } = useGLTF('/marine-mini.gltf');
  const { armRot } = props;
  const bones = [];
  const objArr = Object.keys(nodes);

  for (let i = 0; i < objArr.length; i++) {
    const isBone = nodes[objArr[i]].isBone;
    if (isBone) {
      console.log(objArr[i]);
      bones.push({ name: objArr[i], rot: [0, 0, 0] });
    }
  }

  return (
    <group {...props} dispose={null} scale={0.2}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
      />
      <primitive object={nodes.Bone050}>
        <primitive object={nodes.Bone056}>
          <primitive
            object={nodes.Bone057}
            rotation={[armRot[0], armRot[1], armRot[2]]}
          ></primitive>
        </primitive>
      </primitive>
      <primitive object={nodes.Bone}>
        <primitive object={nodes.Bone001}>
          <primitive object={nodes.Bone024}></primitive>
        </primitive>
      </primitive>
      <primitive object={nodes.Bone049} />
      <skinnedMesh
        geometry={nodes.SNIPER_CADIAN001_1.geometry}
        material={materials['Material.001']}
        skeleton={nodes.SNIPER_CADIAN001_1.skeleton}
      />
      <skinnedMesh
        geometry={nodes.SNIPER_CADIAN001_2.geometry}
        material={materials.tail_04}
        skeleton={nodes.SNIPER_CADIAN001_2.skeleton}
      />
    </group>
  );
}

useGLTF.preload('/marine-mini.gltf');
