/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/skeleton.gltf
*/

import React from 'react';
import { ModelImport } from './modelParts/Skeleton.jsx';
import { HelmetTermie } from './modelParts/HelmetTermie.jsx';
import { FaceTermie } from './modelParts/FaceTermie.jsx';
import { TorsoTermie } from './modelParts/TorsoTermie.jsx';
import { ShoulderTermieRight } from './modelParts/ShoulderTermieRight.jsx';
import { ShoulderTermieLeft } from './modelParts/ShoulderTermieLeft.jsx';
import { ArmTermieRight } from './modelParts/ArmTermieRight.jsx';
import { ArmTermieRightTwo } from './modelParts/ArmTermieRightTwo.jsx';
import { ArmTermieRightAuto } from './modelParts/ArmTermieRightAuto.jsx';
import { ArmTermieLeft } from './modelParts/ArmTermieLeft.jsx';
import { ArmTermieRightFlamer } from './modelParts/ArmTermieRightFlamer.jsx';
import { LegsTermie } from './modelParts/LegsTermie.jsx';
import { BaseTermieLeft } from './modelParts/BaseTermieLeft.jsx';
import { CloakTermie } from './modelParts/CloakTermie.jsx';
import { IronCross } from './modelParts/IronCross.jsx';
export function Model(props) {
  const {
    currentPaint,
    armR,
    arm,
    armRRot,
    attachment,
    head,
    ironCross,
    paintRef,
    show,
  } = props;

  return (
    <group>
      <ModelImport
        torsoBone={props.torsoBone}
        neck={props.neck}
        cloak={
          attachment === 'cloak' ? (
            <CloakTermie
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
            />
          ) : null
        }
        ironCross={
          ironCross === 'ironCross' ? (
            <IronCross
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
            />
          ) : null
        }
        helmet={
          head === 'helmet' ? (
            <HelmetTermie
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
            />
          ) : (
            <FaceTermie
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
            />
          )
        }
        torso={
          <TorsoTermie
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
          />
        }
        shoulderR={
          <ShoulderTermieRight
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
          />
        }
        shoulderL={
          <ShoulderTermieLeft currentPaint={currentPaint} show={show ? 1 : 0} />
        }
        armR={
          armR === 'sword' ? (
            <ArmTermieRightTwo
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
            />
          ) : armR === 'auto' ? (
            <ArmTermieRightAuto
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
            />
          ) : armR === 'flamer' ? (
            <ArmTermieRightFlamer
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
            />
          ) : (
            <ArmTermieRight
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
            />
          )
        }
        armL={
          <ArmTermieLeft
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
          />
        }
        arm={arm}
        armRRot={armRRot}
        legs={
          <LegsTermie
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
          />
        }
        base={
          <BaseTermieLeft
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
          />
        }
        currentPaint={props.currentPaint}
        torsoTopBone={props.torsoTopBone}
        paintRef={paintRef}
      />
    </group>
  );
}
