/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/skeleton.gltf
*/

import React from 'react';
import { ModelImport } from './modelParts/Skeleton.jsx';
import { ArmTermieLeft } from './modelParts/ArmTermieLeft.jsx';
import { LegsTermie } from './modelParts/LegsTermie.jsx';
import { BaseTermieLeft } from './modelParts/BaseTermieLeft.jsx';
import { ModelObject } from './modelParts/ModelObject.jsx';
export function Model(props) {
  const {
    currentPaint,
    armR,
    arm,
    armRRot,
    attachment,
    head,
    ironCross,
    paintRef,
    show,
    lights,
    squadIndex,
    baseColor,
  } = props;

  return (
    <group>
      <ModelImport
        torsoBone={props.torsoBone}
        neck={props.neck}
        cloak={
          attachment === 'cloak' ? (
            <ModelObject
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
              squadIndex={squadIndex}
              url="https://model-painter.s3.eu-west-2.amazonaws.com/terminator_cloak.gltf"
              baseColor={baseColor}
            />
          ) : null
        }
        ironCross={
          ironCross === 'ironCross' ? (
            <ModelObject
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
              squadIndex={squadIndex}
              url="https://model-painter.s3.eu-west-2.amazonaws.com/iron-cross.gltf"
              baseColor={baseColor}
            />
          ) : null
        }
        helmet={
          head === 'helmet' ? (
            <ModelObject
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
              squadIndex={squadIndex}
              url="termie_helmet.glb"
              baseColor={baseColor}
            />
          ) : (
            <ModelObject
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
              squadIndex={squadIndex}
              url="https://model-painter.s3.eu-west-2.amazonaws.com/face_termie.gltf"
              baseColor={baseColor}
            />
          )
        }
        torso={
          <ModelObject
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
            squadIndex={squadIndex}
            url="termie_torso.glb"
            baseColor={baseColor}
          />
        }
        shoulderR={
          <ModelObject
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
            squadIndex={squadIndex}
            url="https://model-painter.s3.eu-west-2.amazonaws.com/shoulder_termie_right.gltf"
            baseColor={baseColor}
          />
        }
        shoulderL={
          <ModelObject
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
            squadIndex={squadIndex}
            url="https://model-painter.s3.eu-west-2.amazonaws.com/shoulder_termie_left.gltf"
            baseColor={baseColor}
          />
        }
        armR={
          armR === 'sword' ? (
            <ModelObject
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
              squadIndex={squadIndex}
              url="https://model-painter.s3.eu-west-2.amazonaws.com/arm_termie_right_two.gltf"
              baseColor={baseColor}
            />
          ) : armR === 'auto' ? (
            <ModelObject
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
              squadIndex={squadIndex}
              url="https://model-painter.s3.eu-west-2.amazonaws.com/arm_termie_right_auto.gltf"
              baseColor={baseColor}
            />
          ) : armR === 'flamer' ? (
            <ModelObject
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
              squadIndex={squadIndex}
              url="https://model-painter.s3.eu-west-2.amazonaws.com/arm_termie_right_flamer.gltf"
              baseColor={baseColor}
            />
          ) : (
            <ModelObject
              currentPaint={currentPaint}
              paintRef={paintRef}
              show={show ? 1 : 0}
              squadIndex={squadIndex}
              url="https://model-painter.s3.eu-west-2.amazonaws.com/arm_termie_right.gltf"
              baseColor={baseColor}
            />
          )
        }
        armL={
          <ModelObject
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
            squadIndex={squadIndex}
            url="https://model-painter.s3.eu-west-2.amazonaws.com/arm_termie_left.gltf"
            baseColor={baseColor}
          />
        }
        arm={arm}
        armRRot={armRRot}
        legs={
          <ModelObject
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
            squadIndex={squadIndex}
            url="termie_leg.glb"
            baseColor={baseColor}
          />
        }
        base={
          <ModelObject
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show ? 1 : 0}
            squadIndex={squadIndex}
            url="https://model-painter.s3.eu-west-2.amazonaws.com/base_termie_left.gltf"
            baseColor={baseColor}
          />
        }
        currentPaint={props.currentPaint}
        torsoTopBone={props.torsoTopBone}
        paintRef={paintRef}
        baseColor={baseColor}
      />
    </group>
  );
}
