/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/skeleton.gltf
*/

import React from 'react';
import { TyranidSkeleton } from './modelParts/TyranidSkeleton.jsx';
import { TyranidBody } from './modelParts/TyranidBody.jsx';
import { TyranidHead } from './modelParts/TyranidHead.jsx';
import { TyranidArm } from './modelParts/TyranidArm.jsx';
import { TyranidArm2 } from './modelParts/TyranidArm2.jsx';
import { TyranidLeg } from './modelParts/TyranidLeg.jsx';
import { TyranidTail } from './modelParts/TyranidTail.jsx';

export function TyranidModel(props) {
  const { currentPaint, paintRef, show } = props;

  return (
    <group>
      <TyranidSkeleton
        torso={
          <TyranidBody
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show}
          />
        }
        head={
          <TyranidHead
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show}
          />
        }
        arm={
          <TyranidArm
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show}
          />
        }
        arm2={
          <TyranidArm2
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show}
          />
        }
        leg={
          <TyranidLeg
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show}
          />
        }
        tail={
          <TyranidTail
            currentPaint={currentPaint}
            paintRef={paintRef}
            show={show}
          />
        }
        currentPaint={props.currentPaint}
        paintRef={paintRef}
      />
    </group>
  );
}
